name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:    
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack one.asai.rampart.csharp/one.asai.rampart.csharp.csproj -o artifacts/
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/teddy-toshi/index.json" -n "github" -u "teddy-toshi" -p ${{secrets.GH_PACKAGES_PAT}} --store-password-in-clear-text
          dotnet nuget push "*.nupkg" --api-key ${{secrets.GH_PACKAGES_PAT}} --source "github" --skip-duplicate
